# Generated by Django 3.0.7 on 2021-08-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodecoddercache',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='geodecoddercache',
            name='long',
            field=models.FloatField(default=None),
        ),
    ]
